name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      # Step 3: Verify Python version
      - name: Check Python version
        run: python --version

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: List files in the tests directory (debugging)
      - name: List files in the tests directory
        run: ls -l tests/

      # Step 6: List all files in the repository (debugging)
      - name: List all files in the repository
        run: ls -l

      # Step 7: Run tests on specific file
      - name: Run tests
        run: pytest tests/tests_operations.py --maxfail=1 --disable-warnings
